name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Composer Kit
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the documentation and confirmed this is unexpected behavior
          required: true
        - label: I am using a supported version of Composer Kit
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which Composer Kit component is affected?
      options:
        - Address
        - Balance
        - Identity
        - NFT
        - Payment
        - Swap
        - Token Select
        - Transaction
        - Wallet
        - Core/Provider
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Install @composer-kit/ui
        2. Import the component...
        3. Configure with...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: tsx
      placeholder: |
        import { ComponentName } from "@composer-kit/ui/component";

        function MyComponent() {
          return (
            <ComponentName
              // your props here
            />
          );
        }

  - type: input
    id: composer-kit-version
    attributes:
      label: Composer Kit Version
      description: What version of @composer-kit/ui are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: blockchain-network
    attributes:
      label: Blockchain Network
      description: Which blockchain network are you using?
      options:
        - Celo Mainnet
        - Celo Alfajores Testnet
        - Other (please specify in additional context)
    validations:
      required: false

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      placeholder: e.g., 18.2.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: false

  - type: dropdown
    id: wallet
    attributes:
      label: Wallet
      description: Which wallet are you using (if applicable)?
      options:
        - MetaMask
        - WalletConnect
        - Coinbase Wallet
        - Valora
        - Other (please specify in additional context)
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or console logs
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute a fix for this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue
          required: false
