name: 📚 Documentation
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear and comprehensive docs are essential for a great developer experience.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your documentation issue
      options:
        - label: I have searched existing issues to ensure this documentation issue hasn't been reported already
          required: true
        - label: I have checked the current documentation thoroughly
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect/Outdated Information
        - Unclear Instructions
        - Missing Code Examples
        - API Reference Issue
        - Installation/Setup Issue
        - Component Usage Guide
        - Migration Guide
        - Accessibility Documentation
        - Performance Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: component-area
    attributes:
      label: Component/Area
      description: Which component or area does this documentation issue relate to?
      options:
        - Address
        - Balance
        - Identity
        - NFT
        - Payment
        - Swap
        - Token Select
        - Transaction
        - Wallet
        - Core/Provider
        - Installation/Setup
        - Getting Started
        - API Reference
        - Examples
        - Migration Guide
        - Contributing Guide
        - General
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: Where is this documentation located? (URL, file path, or section)
      placeholder: e.g., README.md, docs/components/wallet.md, https://...
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Clearly describe the documentation issue
      placeholder: |
        The current documentation...
        This is confusing because...
        It should instead...
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (if applicable)
      description: Quote the current documentation content that needs improvement
      render: markdown
      placeholder: |
        Current documentation says:
        ```
        [paste current content here]
        ```

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      render: markdown
      placeholder: |
        The documentation should say:
        ```
        [your suggested content here]
        ```

  - type: textarea
    id: missing-information
    attributes:
      label: Missing Information
      description: What specific information is missing from the documentation?
      placeholder: |
        The documentation should include:
        - How to handle errors
        - Code examples for common use cases
        - Props explanation
        - etc.

  - type: textarea
    id: code-examples
    attributes:
      label: Requested Code Examples
      description: What code examples would be helpful?
      render: tsx
      placeholder: |
        // Example of what should be documented
        import { Component } from "@composer-kit/ui/component";

        function Example() {
          // Show how to use the component
        }

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - Beginners to React
        - Beginners to Web3
        - Experienced React developers
        - Experienced Web3 developers
        - Library contributors
        - All developers
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor improvement
        - Medium - Would help many developers
        - High - Blocking developer adoption
        - Critical - Incorrect information causing issues
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: How does this documentation issue affect developers using Composer Kit?
      placeholder: |
        This affects developers by...
        It makes it difficult to...
        Developers might...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help improve this documentation?
      options:
        - label: I would be willing to submit a PR to improve this documentation
          required: false
        - label: I would be willing to review documentation improvements
          required: false
